### ISSUE TITLE
[GraalVM 21.3.0.r17] Optaplanner Native Build Failure #992

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus-quickstarts#993]
When using the JAva 17 support of GraalVM 21.3.0, the optaplanner quickstart fails with:

```
Error: Class initialization of com.thoughtworks.xstream.converters.reflection.AbstractAttributedCharacterIteratorAttributeConverter$Reflections failed. Use the option --initialize-at-run-time=com.thoughtworks.xstream.converters.reflection.AbstractAttributedCharacterIteratorAttributeConverter$Reflections to explicitly request delayed initialization of this class.
```

**Comment by ffang** [comment]
Hi @cescoffier ,

We see this problem also in camel-quarkus. We can specify quarkus.native.additional-build-args
-J--add-opens=java.base/java.text=ALL-UNNAMED to workaround it in camel-quarkus. Or this flag will be added in quarkus NativeImageBuildStep.java  by default(like the fix for https://github.com/quarkusio/quarkus/issues/21359)?  Though the root cause is that the com.thoughtworks.xstream should avoid using "non-public deep reflect".

Best Regards
Freeman

**Comment by cescoffier** [comment]
@ffang that's interesting. Adding that to the extension, or declaring a build item could be interesting. 
@Sanne, you did it explicitly. Do you think a build item can be useful?

**Comment by Sanne** [comment]
@cescoffier no I don't think a build item would be useful. I did consider it, but there is no drawback in including the missing modules: it's only about visibility, it's not enforcing their inclusion.

So it's actually better to have a hard-coded list in core (feel free to add this one) than to have to test/validate multiple permutations of such flags.

**Comment by ffang** [comment]
PR sent to address this
https://github.com/quarkusio/quarkus/pull/22005

Thanks @Sanne  @cescoffier !
